default: &default
  APP_NAME: 'Multisearch'
  DB_NAME: 'multisearch'
  DB_HOST: 'localhost'
  DB_PORT: '5432'
  DB_USERNAME: 'postgres'
  MAILER_DEFAULT_HOST: 'localhost'
  MAILER_DEFAULT_PORT: '3000'
  MAILER_SENDER: 'Test <noreply@nimblehq.co>'
  SEARCH_LIMIT: '100'

development:
  <<: *default

test:
  <<: *default
  TEST_RETRY: '0'
